//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

   
    public partial class AdminToolEntities : DbContext
    {
        private static AdminToolEntities _context;
        public AdminToolEntities()
            : base("name=AdminToolEntities")
        {
        }
        public static AdminToolEntities GetContext()
        {
            if (_context == null)
            {
                _context = new AdminToolEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<ModeratorList> ModeratorList { get; set; }
        public virtual DbSet<OnlineList> OnlineList { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableName> TableName { get; set; }
        public virtual DbSet<TypeHistory> TypeHistory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
