//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        public int PlayerID { get; set; }
        public string Steam64 { get; set; }
        public string PlayerNickname { get; set; }
        public string ReasonForBlocking { get; set; }
        public System.DateTime DateTimeBanned { get; set; }
        public Nullable<System.DateTime> DateTimeUnbanned { get; set; }
    }
}
