//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryID { get; set; }
        public int UserID { get; set; }
        public int TableID { get; set; }
        public int RecordID { get; set; }
        public int TypeHistoryID { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual TableName TableName { get; set; }
        public virtual TypeHistory TypeHistory { get; set; }
        public virtual User User { get; set; }
    }
}
