//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineList
    {
        public int OnlineListID { get; set; }
        public int OnServer { get; set; }
        public System.DateTime DateTime { get; set; }
        public int IdUserAddedMeaning { get; set; }
    
        public virtual User User { get; set; }
    }
}
