//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.ModeratorList = new HashSet<ModeratorList>();
        }
    
        public int PlayerID { get; set; }
        public string Steam64 { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string PlayerNickname { get; set; }
        public int IdUserСheckedQuent { get; set; }
        public int IdUserConductedInterview { get; set; }
        public int IdUserAddedSystem { get; set; }
        public bool IsBanned { get; set; }
        public string AdditionalDescription { get; set; }
        public string ReasonForBlocking { get; set; }
        public Nullable<int> IdUserAddedBlock { get; set; }
        public Nullable<System.DateTime> DateTimeBanned { get; set; }
        public Nullable<bool> IsPermanently { get; set; }
        public Nullable<System.DateTime> DateTimeUnbanned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModeratorList> ModeratorList { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
